server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    hikari:
      maximum-pool-size: 5
